name: Test Charmhub Upload

on:
  push:
    branches:
      - "track/*"
      - "master"
  pull_request:
    branches:
      - "track/*"
      - "master"

jobs:
  test-charmhub-upload:
    runs-on: ubuntu-latest
    name: Test charmhub upload
    steps:
      - uses: actions/checkout@v2
      - name: Select charmhub channel
        uses: ./channel
        id: channel
      - name: Upload charm to charmhub
        uses: ./upload-charm
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          charm-path: test-charm/
          upload-image: "true"
          channel: ${{ steps.channel.outputs.name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./upload-bundle
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          bundle-path: test-bundle/
          github-token: ${{ secrets.GITHUB_TOKEN }}